export const GET_ARTICLES = "GET_ARTICLES";
export const GET_ARTICLES_SUCCESS="GET_ARTICLES_SUCCESS";
export const GET_ARTICLES_FAILURE="GET_ARTICLES_FAILURE";
export const GET_ARTICLE = "GET_ARTICLE";
export const GET_ARTICLE_SUCCESS="GET_ARTICLE_SUCCESS";
export const GET_ARTICLE_FAILURE="GET_ARTICLE_FAILURE";